# multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#db
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=kh16
spring.datasource.password=kh16

#dbcp (datebase connection pool)
spring.datasource.dbcp2.max-total=20
#spring.datasource.dbcp2.min-idle=5
spring.datasource.dbcp2.max-idle=5